version: '2'
services:
  jenkins:
    image: merapar/jenkins-container:latest
    restart: always
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/jenkins/:/var/jenkins_home
      - /root/.ssh:/root/.ssh
    environment:
      - TZ=Europe/Amsterdam
